
networks:
  test:
    name: fastapi-nexus4-network

services:
  mysql_db:
    image: mysql:8.0.31
    container_name: mysql_nexus4
    volumes:
      - ./BBDD.sql:/docker-entrypoint-initdb.d/BBDD.sql
    ports:
      - 3306:3306
    networks:
      - test
    environment:
      - MYSQL_DATABASE=nexus4
      - MYSQL_USER=admin_db
      - MYSQL_PASSWORD=admin_db
      - MYSQL_ROOT_PASSWORD=toor
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

  fastapi:
    image: nexus-4:latest  # Usa la imagen construida por build.sh
    container_name: nexus4_fastapi
    restart: always
    ports: 
      - 8000:8000
    networks:
      - test
    environment:
      - MYSQL_URL=mysql://root:toor@mysql_nexus4:3306/nexus4
    volumes:
      - ./app:/code/app
    depends_on:
      mysql_db:
        condition: service_healthy

  sphinx:
    image: nexus-4:latest  # Usa la misma imagen para Sphinx
    container_name: nexus4_sphinx
    command: sphinx-build -b html docs/source docs/build
    volumes:
      - ./docs:/code/docs
    networks:
      - test
    depends_on:
      - fastapi