name: Run Tests

on:
  push:
    branches:
      - main
      - Developer
  pull_request:
    branches:
      - main
      - Developer

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.31
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: toor
          MYSQL_DATABASE: nexus4
          MYSQL_USER: admin_db
          MYSQL_PASSWORD: admin_db
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u admin_db --password=admin_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Wait for MySQL to be ready
      run: |
        while ! mysqladmin ping -h"127.0.0.1" -u admin_db --password=admin_db --silent; do
          echo "Waiting for database connection..."
          sleep 2
        done

    - name: Run tests
      run: |
        source venv/bin/activate
        pytest
      env:
        DATABASE_URL: mysql://admin_db:admin_db@127.0.0.1:3306/nexus4