name: Run Tests

on:
  push:
    branches:
      - main
      - Developer
  pull_request:
    branches:
      - main
      - Developer

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the code
      - name: Check out repository
        uses: actions/checkout@v3

      # 2. Set up Docker Compose
      - name: Set up Docker Compose
        run: docker-compose up --build -d

      # 3. Wait for MySQL to be ready
      - name: Wait for MySQL to be ready
        run: |
          for i in {1..30}; do
            docker inspect --format='{{json .State.Health.Status}}' mysql_nexus4 | grep -q "healthy" && break
            echo "Waiting for MySQL to be ready..."
            sleep 5
          done

      # 4. Run tests inside the FastAPI container
      - name: Run API tests
        run: |
          docker exec nexus4_fastapi pytest
        env:
          DATABASE_URL: mysql://root:toor@mysql_nexus4:3306/nexus4

      # 5. Shut down Docker Compose
      - name: Shut down Docker Compose
        if: always()
        run: docker-compose down
